-- ============================================================
-- TI-PR-01  Programa de Mantenimiento de Equipos Tecnologicos
-- DDL corregido. NO EJECUTADO todavia.
--
-- ALCANCE:
--   1. programas_mantenimiento
--   2. programa_mantenimiento_unidades
--   3. programacion_mantenimiento
--
-- NO modifica vehiculos ni mantenimientos_tecnicos.
--
-- DECISIONES FUNCIONALES APLICADAS:
--   * UNIQUE (programa_unidad_id, fecha_programada) se mantiene a proposito:
--     M2 incluye las actividades de M1 y M3 incluye M1 + M2, por lo que cuando
--     los niveles coinciden en una fecha debe existir UN SOLO registro.
--     El generador (fuera de este alcance) aplicara prioridad M3 > M2 > M1.
--   * created_at / updated_at en timestamptz, aunque las tablas antiguas usen
--     timestamp without time zone.
--   * FK hacia vehiculos(placa): ON UPDATE CASCADE ON DELETE RESTRICT.
--   * Sin estructura por equipos: las frecuencias M1/M2/M3 son generales del programa.
--   * Sin CHECK de workflow (EJECUTADO -> fecha_ejecucion, etc.): aun no esta cerrado.
--
-- Verificado contra la branch de pruebas de Neon (PostgreSQL 18.6) en solo lectura:
--   - las tres tablas no existen;
--   - vehiculos.placa es character varying(20) NOT NULL y PRIMARY KEY;
--   - ningun nombre de tabla, constraint, indice, secuencia, trigger o funcion colisiona.
-- ============================================================


-- ============================================================
-- 0. FUNCION PARA updated_at
--    Nombre sin prefijo fn_, como el resto de funciones de la base
--    (set_fecha_cese_personal, validar_cierre_ticket_unidad, actualizar_estado_inspeccion).
--    Es generica y reutilizable por cualquier tabla con columna updated_at.
-- ============================================================

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;


-- ============================================================
-- 1. CABECERA DEL PROGRAMA
-- ============================================================

CREATE TABLE programas_mantenimiento (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    codigo varchar(30) NOT NULL,
    nombre varchar(200) NOT NULL,

    periodo_inicio date NOT NULL,
    periodo_fin date NOT NULL,

    version varchar(20) NOT NULL,
    fecha_documento date NOT NULL,

    frecuencia_m1_dias integer NOT NULL,
    frecuencia_m2_dias integer NOT NULL,
    frecuencia_m3_dias integer NOT NULL,

    estado varchar(20) NOT NULL DEFAULT 'ACTIVO',

    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_programas_mantenimiento_periodo
        CHECK (periodo_fin >= periodo_inicio),

    CONSTRAINT chk_programas_mantenimiento_frecuencia_m1
        CHECK (frecuencia_m1_dias > 0),

    CONSTRAINT chk_programas_mantenimiento_frecuencia_m2
        CHECK (frecuencia_m2_dias > 0),

    CONSTRAINT chk_programas_mantenimiento_frecuencia_m3
        CHECK (frecuencia_m3_dias > 0),

    CONSTRAINT chk_programas_mantenimiento_estado
        CHECK (
            estado IN (
                'ACTIVO',
                'CERRADO',
                'ANULADO'
            )
        ),

    CONSTRAINT uq_programas_mantenimiento_codigo_periodo_version
        UNIQUE (
            codigo,
            periodo_inicio,
            version
        )
);


CREATE TRIGGER trg_set_updated_at_programas_mantenimiento
BEFORE UPDATE ON programas_mantenimiento
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


-- ============================================================
-- 2. UNIDADES INCLUIDAS EN CADA PROGRAMA
-- ============================================================

CREATE TABLE programa_mantenimiento_unidades (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    programa_id integer NOT NULL,

    placa varchar(20) NOT NULL,

    fecha_base_m1 date,
    fecha_base_m2 date,
    fecha_base_m3 date,

    quincena_arranque date,

    observaciones text,

    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_programa_unidad_programa
        FOREIGN KEY (programa_id)
        REFERENCES programas_mantenimiento(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_programa_unidad_vehiculo
        FOREIGN KEY (placa)
        REFERENCES vehiculos(placa)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uq_programa_mantenimiento_unidad
        UNIQUE (
            programa_id,
            placa
        )
);


-- placa va en segunda posicion dentro del UNIQUE, por lo que necesita indice propio
-- para las verificaciones de la FK hacia vehiculos.
CREATE INDEX idx_programa_mantenimiento_unidades_placa
    ON programa_mantenimiento_unidades(placa);


CREATE TRIGGER trg_set_updated_at_programa_mantenimiento_unidades
BEFORE UPDATE ON programa_mantenimiento_unidades
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


-- ============================================================
-- 3. EVENTOS PROGRAMADOS
-- ============================================================

CREATE TABLE programacion_mantenimiento (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    programa_unidad_id integer NOT NULL,

    fecha_programada date NOT NULL,

    nivel_mantenimiento varchar(2) NOT NULL,

    estado varchar(20) NOT NULL DEFAULT 'PROGRAMADO',

    fecha_reprogramada date,
    fecha_ejecucion date,

    observaciones text,

    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_programacion_mantenimiento_unidad
        FOREIGN KEY (programa_unidad_id)
        REFERENCES programa_mantenimiento_unidades(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_programacion_mantenimiento_nivel
        CHECK (
            nivel_mantenimiento IN (
                'M1',
                'M2',
                'M3'
            )
        ),

    CONSTRAINT chk_programacion_mantenimiento_estado
        CHECK (
            estado IN (
                'PROGRAMADO',
                'EJECUTADO',
                'NO_EJECUTADO',
                'REPROGRAMADO',
                'CANCELADO'
            )
        ),

    -- Un unico evento por unidad y fecha: cuando los niveles coinciden,
    -- el generador conserva solo el de mayor jerarquia (M3 > M2 > M1).
    CONSTRAINT uq_programacion_mantenimiento_unidad_fecha
        UNIQUE (
            programa_unidad_id,
            fecha_programada
        )
);


CREATE INDEX idx_programacion_mantenimiento_fecha
    ON programacion_mantenimiento(fecha_programada);


CREATE INDEX idx_programacion_mantenimiento_estado_fecha
    ON programacion_mantenimiento(estado, fecha_programada);


CREATE TRIGGER trg_set_updated_at_programacion_mantenimiento
BEFORE UPDATE ON programacion_mantenimiento
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();
