-- ============================================================
-- TI-PR-01  FASE A - EXPANSION
-- Normalizacion por equipos y quincenas.
-- Incremental sobre 20260918_001. NO EJECUTADO todavia.
--
-- ESTA FASE ES 100% ADITIVA:
--   * NO renombra ninguna columna existente.
--   * NO elimina ninguna columna existente.
--   * NO cambia tipos ni nulabilidad de nada existente.
--   * NO inserta, actualiza ni borra datos.
--   * NO toca inspecciones_flota ni mantenimientos_tecnicos.
--
-- Por eso el backend publicado (modulo programas/unidades) sigue
-- funcionando e initDb() sigue pasando: todas las columnas que su
-- contrato exige continuan existiendo.
--
-- REGLAS DE NEGOCIO QUE IMPLEMENTA:
--   * La planificacion trabaja por QUINCENAS, ancladas en dia 1 o 16.
--     El ancla es administrativa: no obliga a ejecutar ese dia.
--   * Periodicidad por equipo y nivel, en quincenas:
--       DVR / COPILOTO / RADIO_BASE / CAMARAS -> M1=1, M2=6, M3=12
--       GPS -> solo M3 = 24
--   * GPS solo admite M3. La regla vive UNICAMENTE en
--     programa_mantenimiento_frecuencias; las tablas hijas la heredan
--     mediante FK compuesta (programa_id, tipo_equipo, nivel_mantenimiento).
--   * Una visita por unidad y quincena efectiva. Las visitas CANCELADO
--     liberan la quincena.
--   * fecha_ejecucion es el dia real y NO gobierna el ciclo.
--     ultima_fecha_real es documental y tampoco gobierna el ciclo.
--
-- Requiere set_updated_at(), creada en 20260918_001.
-- ============================================================


-- ------------------------------------------------------------
-- 1. vehiculos: inventario de equipos por unidad
--    TRUE  = confirmado que la unidad tiene el equipo
--    FALSE = confirmado que no lo tiene
--    NULL  = inventario pendiente de definir (por eso no hay DEFAULT)
-- ------------------------------------------------------------
ALTER TABLE vehiculos
  ADD COLUMN dvr_instalado        boolean,
  ADD COLUMN copiloto_instalado   boolean,
  ADD COLUMN radio_base_instalado boolean,
  ADD COLUMN camaras_instaladas   boolean,
  ADD COLUMN gps_instalado        boolean;


-- ------------------------------------------------------------
-- 2. Catalogo autoritativo: periodicidad por equipo y nivel
--    Unico lugar donde vive el dominio de equipo/nivel y la regla del GPS.
-- ------------------------------------------------------------
CREATE TABLE programa_mantenimiento_frecuencias (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    programa_id integer NOT NULL,
    tipo_equipo varchar(20) NOT NULL,
    nivel_mantenimiento varchar(2) NOT NULL,
    frecuencia_quincenas smallint NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_frecuencia_programa
        FOREIGN KEY (programa_id)
        REFERENCES programas_mantenimiento(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_frecuencia_tipo_equipo
        CHECK (
            tipo_equipo IN (
                'DVR',
                'COPILOTO',
                'RADIO_BASE',
                'CAMARAS',
                'GPS'
            )
        ),

    CONSTRAINT chk_frecuencia_nivel
        CHECK (
            nivel_mantenimiento IN (
                'M1',
                'M2',
                'M3'
            )
        ),

    -- Regla de negocio definitiva: si es GPS entonces solo M3.
    CONSTRAINT chk_frecuencia_gps_solo_m3
        CHECK (
            tipo_equipo <> 'GPS'
            OR nivel_mantenimiento = 'M3'
        ),

    CONSTRAINT chk_frecuencia_quincenas
        CHECK (frecuencia_quincenas > 0),

    -- Destino de las FK compuestas de las tablas hijas.
    CONSTRAINT uq_frecuencia_programa_equipo_nivel
        UNIQUE (
            programa_id,
            tipo_equipo,
            nivel_mantenimiento
        )
);

CREATE TRIGGER trg_set_updated_at_programa_mantenimiento_frecuencias
BEFORE UPDATE ON programa_mantenimiento_frecuencias
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


-- ------------------------------------------------------------
-- 3. programa_mantenimiento_unidades
--    Se AGREGA quincena_incorporacion (desde cuando participa la unidad).
--    NO es base de ciclo: la base vive en programa_mantenimiento_unidad_ciclos.
--    quincena_arranque y fecha_base_m1/m2/m3 se CONSERVAN: el backend
--    publicado todavia las usa. Se retiran en la fase de limpieza.
-- ------------------------------------------------------------
ALTER TABLE programa_mantenimiento_unidades
  ADD CONSTRAINT uq_programa_unidad_id_programa
      UNIQUE (id, programa_id);

ALTER TABLE programa_mantenimiento_unidades
  ADD COLUMN quincena_incorporacion date;

ALTER TABLE programa_mantenimiento_unidades
  ADD CONSTRAINT chk_programa_unidad_quincena_incorporacion
      CHECK (
          quincena_incorporacion IS NULL
          OR EXTRACT(DAY FROM quincena_incorporacion) IN (1, 16)
      ) NOT VALID;


-- ------------------------------------------------------------
-- 4. Continuidad del ciclo por unidad + equipo + nivel
--    La ausencia de fila significa REFERENCIA PENDIENTE DE CARGA:
--    nunca se crea una fila con referencia vacia o inventada.
--    Sin CHECK de dominio de equipo/nivel: los hereda del catalogo por FK.
-- ------------------------------------------------------------
CREATE TABLE programa_mantenimiento_unidad_ciclos (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    programa_unidad_id integer NOT NULL,
    programa_id integer NOT NULL,
    tipo_equipo varchar(20) NOT NULL,
    nivel_mantenimiento varchar(2) NOT NULL,

    -- Ancla administrativa: es la unica que gobierna el calculo del ciclo.
    ultima_quincena date NOT NULL,

    -- Evidencia documental del dia real, si se conoce. NO gobierna el ciclo
    -- y puede caer en otra quincena (ejecucion anticipada).
    ultima_fecha_real date,

    fuente varchar(30) NOT NULL,
    observaciones text,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_ciclo_unidad
        FOREIGN KEY (programa_unidad_id, programa_id)
        REFERENCES programa_mantenimiento_unidades(id, programa_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_ciclo_frecuencia
        FOREIGN KEY (programa_id, tipo_equipo, nivel_mantenimiento)
        REFERENCES programa_mantenimiento_frecuencias
                   (programa_id, tipo_equipo, nivel_mantenimiento)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uq_ciclo_unidad_equipo_nivel
        UNIQUE (
            programa_unidad_id,
            tipo_equipo,
            nivel_mantenimiento
        ),

    -- Controles propios de esta entidad, no cubiertos por la FK.
    CONSTRAINT chk_ciclo_ultima_quincena
        CHECK (EXTRACT(DAY FROM ultima_quincena) IN (1, 16)),

    CONSTRAINT chk_ciclo_fuente
        CHECK (
            fuente IN (
                'INSPECCIONES_FLOTA',
                'MANTENIMIENTOS_TECNICOS',
                'EXCEL',
                'MANUAL'
            )
        )
);

CREATE TRIGGER trg_set_updated_at_programa_mantenimiento_unidad_ciclos
BEFORE UPDATE ON programa_mantenimiento_unidad_ciclos
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


-- ------------------------------------------------------------
-- 5. programacion_mantenimiento: la visita
--    Se AGREGAN las columnas nuevas y conviven con las antiguas.
--    fecha_programada, fecha_reprogramada y nivel_mantenimiento se
--    CONSERVAN porque el contrato de initDb() las exige por nombre.
--
--    quincena_programada   = quincena originalmente planificada
--    quincena_reprogramada = nueva quincena formalmente asignada
--    quincena_efectiva     = la que manda para el ciclo
--    fecha_ejecucion       = dia real, NO mueve el ciclo (sin CHECK)
-- ------------------------------------------------------------
ALTER TABLE programacion_mantenimiento
  ADD COLUMN programa_id integer,
  ADD COLUMN quincena_programada date,
  ADD COLUMN quincena_reprogramada date;

-- Columna generada: se agrega aparte, con sus columnas base ya creadas.
ALTER TABLE programacion_mantenimiento
  ADD COLUMN quincena_efectiva date
      GENERATED ALWAYS AS (
          COALESCE(quincena_reprogramada, quincena_programada)
      ) STORED;

ALTER TABLE programacion_mantenimiento
  ADD CONSTRAINT uq_programacion_id_programa
      UNIQUE (id, programa_id);

ALTER TABLE programacion_mantenimiento
  ADD CONSTRAINT fk_programacion_unidad_programa
      FOREIGN KEY (programa_unidad_id, programa_id)
      REFERENCES programa_mantenimiento_unidades(id, programa_id)
      ON UPDATE CASCADE
      ON DELETE RESTRICT
      NOT VALID;

ALTER TABLE programacion_mantenimiento
  ADD CONSTRAINT chk_programacion_quincena_programada
      CHECK (
          quincena_programada IS NULL
          OR EXTRACT(DAY FROM quincena_programada) IN (1, 16)
      ) NOT VALID,
  ADD CONSTRAINT chk_programacion_quincena_reprogramada
      CHECK (
          quincena_reprogramada IS NULL
          OR EXTRACT(DAY FROM quincena_reprogramada) IN (1, 16)
      ) NOT VALID;

-- Una sola visita efectiva por unidad y quincena.
-- Las visitas CANCELADO quedan fuera del indice y liberan la quincena.
--
-- CONVIVENCIA TEMPORAL CON EL UNIQUE LEGACY
--   Durante las fases A -> B -> B-bis -> C sigue activo el constraint antiguo
--   uq_programacion_mantenimiento_unidad_fecha (programa_unidad_id, fecha_programada),
--   creado por 20260918_001. Ese constraint NO excluye las visitas CANCELADO.
--
--   Consecuencia comprobada en pruebas: mientras exista, una visita CANCELADA
--   todavia NO libera realmente su fecha/quincena legacy. Al intentar crear otra
--   visita para la misma unidad y fecha_programada, el rechazo proviene del
--   constraint antiguo (23505 uq_programacion_mantenimiento_unidad_fecha),
--   no de este indice.
--
--   La regla final del negocio es la de ESTE indice parcial: una sola visita
--   efectiva por unidad y quincena, con las canceladas liberando su lugar.
--   Esa semantica entra en vigor recien cuando la FASE D
--   (20260918_003_..._cleanup.sql) retire el UNIQUE legacy.
CREATE UNIQUE INDEX uq_programacion_unidad_quincena_efectiva
    ON programacion_mantenimiento (programa_unidad_id, quincena_efectiva)
    WHERE estado <> 'CANCELADO';


-- ------------------------------------------------------------
-- 6. Detalle de equipos por visita
--    Un equipo aparece como maximo una vez por visita.
--    Cuando coinciden varios niveles del mismo equipo, el generador
--    debe elegir el mayor (M3 > M2 > M1); la base solo impide el duplicado.
--    Sin CHECK de dominio: equipo+nivel se validan contra el catalogo.
-- ------------------------------------------------------------
CREATE TABLE programacion_mantenimiento_equipos (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    programacion_id integer NOT NULL,
    programa_id integer NOT NULL,
    tipo_equipo varchar(20) NOT NULL,
    nivel_mantenimiento varchar(2) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_programacion_equipo_visita
        FOREIGN KEY (programacion_id, programa_id)
        REFERENCES programacion_mantenimiento(id, programa_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_programacion_equipo_frecuencia
        FOREIGN KEY (programa_id, tipo_equipo, nivel_mantenimiento)
        REFERENCES programa_mantenimiento_frecuencias
                   (programa_id, tipo_equipo, nivel_mantenimiento)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uq_programacion_equipo
        UNIQUE (programacion_id, tipo_equipo)
);

CREATE INDEX idx_programacion_equipos_tipo_nivel
    ON programacion_mantenimiento_equipos(tipo_equipo, nivel_mantenimiento);

CREATE TRIGGER trg_set_updated_at_programacion_mantenimiento_equipos
BEFORE UPDATE ON programacion_mantenimiento_equipos
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();
